x = input('Digite um valor ')
print("O valor digitado é do tipo primitivo: {}".format(type(x)))
print("O valor digitado é numérico? - {}".format(x.isnumeric()))
print("O valor digitado é letras? - {}".format(x.isalpha()))
print("O valor digitado é alphanumérico? - {}".format(x.isalnum()))
print("O valor digitado é unicamente espaços? - {}".format(x.isspace()))
print("O valor digitado está em maiúsculas? - {}".format(x.isupper()))
print("O valor digitado está em minúsculas? - {}".format(x.lower()))
print("O valor digitado está capitalizado? - {}".format(x.istitle()))